# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ecf2c9449e44d3dc1b36f0a0f5d65876530cfd5027c0a23e2216e2863dcab36f45624db0ab98615cf360583389cf9b6e927b751b9f5d38d05764f7adc51b2a1

test:
  secret_key_base: 3f45d76a579d2be9de9130a6d7b2bbc0a77e2af684526408b3d6e1ec5cd2c4865f99cfd47912c3ab0b3505d8f0265c7dceb3983c6e7dd019c7960de8e46c7bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
